-- DEFINIERA VILLKOREN PÅ TABELLER 

/*
ON DELETE CASCADE --BRA NÄR DU HAR SVAG-STARK FÖRHÅLLANDE
ON DELETE SET NULL --BRA OM DU HAR EN FK SOM INTE HAR "NOT NULL" FRAMFÖR
ON DELETE SET DEFAULT --BRA OM DU HAR EN FK SOM HAR ETT DEFAULT VÄRDE.
*/

-- PRIMÄRNYCKLAR 

ALTER TABLE DISCGOLF_CLUB ADD CONSTRAINT PRIMARY KEY (CLUB_ID);

ALTER TABLE HAVE ADD CONSTRAINT PRIMARY KEY (SPONSOR_ID, CLUB_ID);

ALTER TABLE SPONSOR ADD CONSTRAINT PRIMARY KEY (SPONSOR_ID);

ALTER TABLE CONSISTS_OF ADD CONSTRAINT PRIMARY KEY (BOARD_MEMBER_ID, CLUB_ID);

ALTER TABLE BOARD_MEMBER ADD CONSTRAINT PRIMARY KEY (BOARD_MEMBER_ID);

ALTER TABLE PLAYING ADD CONSTRAINT PRIMARY KEY (MEMBER_ID, COMPETITION_ID);

ALTER TABLE COMPETITION ADD CONSTRAINT PRIMARY KEY (COMPETITION_ID);

ALTER TABLE COURSE ADD CONSTRAINT PRIMARY KEY (COURSE_ID);

-- FRÄMMANDE NYCKLAR 

ALTER TABLE HAVE ADD CONSTRAINT HAVE_SPONSOR_FK FOREIGN KEY (SPONSOR_ID) REFERENCES SPONSOR(SPONSOR_ID) ON DELETE CASCADE;
ALTER TABLE HAVE ADD CONSTRAINT HAVE_DISCGOLF_CLUB_FK FOREIGN KEY (CLUB_ID) REFERENCES DISCGOLF_CLUB(CLUB_ID) ON DELETE CASCADE;

ALTER TABLE CONSISTS_OF ADD CONSTRAINT CONSISTS_OF_BOARD_MEMBER_FK FOREIGN KEY (BOARD_MEMBER_ID) REFERENCES BOARD_MEMBER(BOARD_MEMBER_ID);
ALTER TABLE CONSISTS_OF ADD CONSTRAINT CONSISTS_OF_DISCGOLF_CLUB_FK FOREIGN KEY (CLUB_ID) REFERENCES DISCGOLF_CLUB(CLUB_ID);

ALTER TABLE MEMBER ADD CONSTRAINT MEMBER_DISCGOLF_CLUB_FK FOREIGN KEY (CLUB_ID) REFERENCES DISCGOLF_CLUB(CLUB_ID);

ALTER TABLE PLAYING ADD CONSTRAINT PLAYING_MEMBER_FK FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER(MEMBER_ID) ON DELETE CASCADE;
ALTER TABLE PLAYING ADD CONSTRAINT PLAYING_COMPETITION_FK FOREIGN KEY (COMPETITION_ID) REFERENCES COMPETITION(COMPETITION_ID) ON DELETE CASCADE;

ALTER TABLE COMPETITION ADD CONSTRAINT COMPETITION_COURSE_FK FOREIGN KEY (COURSE_ID) REFERENCES COURSE(COURSE_ID);