--Tar bort alla tabeller

DROP TABLE PLAYING; 
DROP TABLE COMPETITION;
DROP TABLE CONSISTS_OF;
DROP TABLE HAVE;   
DROP TABLE COURSE;
DROP TABLE MEMBER; 
DROP TABLE BOARD_MEMBER; 
DROP TABLE SPONSOR; 
DROP TABLE DISCGOLF_CLUB; 